### ISSUE TITLE
Errors on start

### ISSUE THREAD

**Issue by ARTdrakon** [mgerb/ServerStatus#4]
I'm getting this errors

On Windows:
`invalid character '.' after object key:value pair`

On Debian 8.9:
```
2017/12/11 14:14:45 invalid character '.' after object key:value pair
error obtaining account details, HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a0e7]

goroutine 1 [running]:
panic(0x678e20, 0xc42000c0a0)
        /opt/go/src/runtime/panic.go:500 +0x1a1
_/home/ubuntu/workspace/serverstatus/src/bot.Connect(0x0, 0x0)
        /home/ubuntu/workspace/serverstatus/src/bot/bot.go:31 +0x277
main.main()
        /home/ubuntu/workspace/serverstatus/src/main.go:19 +0x42
```

**Comment by mgerb** [comment]
Looks like you may have an error in your config file. It must be in correct JSON format or it will not work. I just tested the bot out and it works fine. If I enter an invalid bot token I get that same 401 error.

**Comment by ARTdrakon** [comment]
Yepp, that one comma you forgot to put somewhere that breaks everything.
